### PR TITLE
Make protected methods public

### PR DESCRIPTION
**Pull request by nadar**
See #70

### CODE REVIEW

**Review by bizley — APPROVED** [review]

**Comment by rob006** [comment]
Changing visibility in that way is a BC break - it will result fatal error if someone overwrites these methods preserving previous (protected) visibility.

**Comment by nadar** [comment]
@rob006 sure, then lets make another major release, should not be a problem at all?

**Comment by bizley** [comment]
Right. What about adding new method?

**Comment by nadar** [comment]
Sure, if releasing a new version is such a pain, then yes... Suggestions?

**Comment by bizley** [comment]
@samdark what do you think?

**Comment by rob006** [comment]
I would not introduce another duplicated method just to widen visibility. It just complicates API, so it is just worse on long run.  Changing this in next major release (2.4.0) is fine, but IMO this change in not enough to trigger such release. You can already quite easily bypass current limitations, by extending this class, then you can widen visibility.

**Comment by nadar** [comment]
> Changing this in next major release (2.4.0) is fine, but IMO this change in not enough to trigger such release.

So what should then happen in future to have such a release? Is there something planed? I don't think so. Activity on that repo is already low. Yii3 is coming. What are we waiting for?

**Review by samdark — APPROVED** [review]

**Comment by samdark** [comment]
Thanks.

**Comment by samdark** [comment]
I think it is OK to make these public under current circumstances.

**Comment by nadar** [comment]
Thanks @samdark

**Pull request merged**
