### PR TITLE
Fixes #54: Adjusted imagick package constraint to allow using latest version

### LINKED ISSUE #54: update imagine/imagine version to 1.1.0?
update imagine/imagine version to 1.1.0?

### PR DESCRIPTION
**Pull request by samdark**
| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | no
| Breaks BC?    | ?
| Tests pass?   | ?
| Fixed issues  | #54

### CODE REVIEW

**Comment by samdark** [comment]
Seems the tests fail with imagick 3.4.4 that is shipped with newer travis images. It was passing with 3.4.3.

**Comment by samdark** [comment]
https://forum.remirepo.net/viewtopic.php?id=3850

**Comment by samdark** [comment]
3.4.4 seems to be missing `\Imagick::setImageAlpha()` while `\Imagick::setImageOpacity()` is throwing deprecation warning.

https://github.com/avalanche123/Imagine/blob/develop/src/Imagick/Imagine.php#L106

**Comment by samdark** [comment]
`\Imagick::setImageAlpha()` was added in ImageMagick 7. ImageMagick 6.7.7-10 is used in travis.

**Comment by samdark** [comment]
So presence of `\Imagick::setImageAlpha()` depends on underlying ImageMagick used.

**Comment by samdark** [comment]
https://github.com/Imagick/imagick/issues/288

**Comment by samdark** [comment]
https://github.com/avalanche123/Imagine/issues/715

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2-imagine/issues/59

**Comment by jackhhh** [comment]
> 3.4.4 seems to be missing `\Imagick::setImageAlpha()` while `\Imagick::setImageOpacity()` is throwing deprecation warning.
> 
> https://github.com/avalanche123/Imagine/blob/develop/src/Imagick/Imagine.php#L106

Why not also include the error ignoring phases to avoid an unnecessary downgrade?

**Pull request merged**
