### PR TITLE
Fix imagine constraint to allow dev-develop

### PR DESCRIPTION
**Pull request by SDKiller**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any

```
{
    "name": "my-project",
    "type": "project",
    "minimum-stability": "stable",
    "require": {
        ...
        "yiisoft/yii2-imagine": "dev-master",
        "imagine/imagine": "dev-develop",
         ...
      }
}
```

> Your requirements could not be resolved to an installable set of packages.

>  Problem 1
>    - Installation request for yiisoft/yii2-imagine dev-master -> satisfiable by yiisoft/yii2-imagine[dev-master].
>    - yiisoft/yii2-imagine dev-master requires imagine/imagine ~0.6.0 -> satisfiable by imagine/imagine[0.6.2, v0.6.0, v0.6.1, v0.6.3] but these conflict with your requirements or minimum-stability.

### CODE REVIEW

**Comment by rob006** [comment]
This change is invalid - it will allow install all 0.x versions, but only 0.6 is compatible with this extension.

**Comment by SDKiller** [comment]
As I can see from https://getcomposer.org/doc/articles/versions.md#tilde this will not allow `0.5.x` versions

**Comment by rob006** [comment]
It still assumes that it will be compatible with 0.7, 0.8, 0.9 etc which probably is not true.

**Comment by samdark** [comment]
Would not merge it for the reasons @rob006 voiced.

**Pull request closed without merging**
